[lint]
select = ["ALL"]
ignore = [
        "ANN201",       
        "E501",    
        "COM812",
        "D100",
        "D101",
        "D102",
        "D103",
        "D107",
        "DTZ007",  
        "DTZ011",         
        "EM101",    
        "EM102",    
        "INP001",
        "N999",
        "PLR2004",  
        "RET505",
        "S101",
        "S110",
        "T201",
        "TRY003",
        "SIM105", 
        "PERF203"
        ]
          